### ISSUE TITLE
Delete all axios POST, PUT, & PATCH JSON.Stringify

### ISSUE THREAD

**Issue by charlesjavelona** [UnivJobs/univjobs-front#14]
Finally! We were able to figure out the reason for most REQUEST errors. JSON.stringify is a big no no when doing a REQUEST. Axios already handles all of that for us.

@stemmlerjs, for future reference, as much as possible we send a standard JSON array without JSON.stringify unless stated otherwise.

**Comment by stemmlerjs** [comment]
Which request errors were affected?
IE: what needs to be fixed?

Makes sense this would cause trouble if we're double stringifying.

**Comment by charlesjavelona** [comment]
Once I finish the apply job,  I will test the other request to see if this issue is all true on each one or its just the Post call. I'll upload a pic of the error tomorrow to show the data structure when it is stringified.

**Comment by charlesjavelona** [comment]
Need to test the following POST & PUT calls:
 - [ ] Createjob
 - [ ] more coming ...

**Comment by charlesjavelona** [comment]
Now testing Createjob:

**Comment by charlesjavelona** [comment]
Fixed the new jobs view by changing the db schema.
Now working on questions. 

**To do for Questions**
- [ ] Make axios POST work for endpoint 'job/new/questions'

**Comment by charlesjavelona** [comment]
Done
