### ISSUE TITLE
Categories Images

### ISSUE THREAD

**Issue by stemmlerjs** [UnivJobs/univjobs-front#24]
![freelanceedited](https://cloud.githubusercontent.com/assets/6892666/25756968/c0983fe8-3196-11e7-8bc6-1ccc40ee200d.jpg)
![onetimegigedited](https://cloud.githubusercontent.com/assets/6892666/25756967/c09784b8-3196-11e7-96d4-6342ef016bb2.jpg)
![parttimeedited](https://cloud.githubusercontent.com/assets/6892666/25756969/c0985cb2-3196-11e7-8c13-0435e14adff1.jpg)
![summeredited](https://cloud.githubusercontent.com/assets/6892666/25756970/c098cd0a-3196-11e7-9216-06826ac6aa46.jpg)
![winteredited](https://cloud.githubusercontent.com/assets/6892666/25756971/c09abd68-3196-11e7-8e1a-035e2106ae86.jpg)
![campusreb_bbedited](https://cloud.githubusercontent.com/assets/6892666/25756972/c0b007cc-3196-11e7-94ba-68c246fde92b.jpg)

**Comment by charlesjavelona** [comment]
![un](https://user-images.githubusercontent.com/7959179/28494401-6a43e046-6efb-11e7-8f90-d0101f47a36b.png)

**Comment by charlesjavelona** [comment]
![rsz_artboard_2](https://user-images.githubusercontent.com/7959179/28494510-ebb6580e-6efe-11e7-867e-4a6ccca4a3f2.png)

**Comment by charlesjavelona** [comment]
![rsz_artboard_2-min](https://user-images.githubusercontent.com/7959179/28494611-6438a780-6f01-11e7-93c0-816a32d292b3.png)

**Comment by charlesjavelona** [comment]
![rsz_artboard_2 2 1](https://user-images.githubusercontent.com/7959179/28494764-132e7a90-6f06-11e7-9a67-10322b90489b.png)

**Comment by charlesjavelona** [comment]
![group-background](https://user-images.githubusercontent.com/7959179/28504965-ffa105fa-6fec-11e7-854d-7467dac1e0e7.jpg)

**Comment by charlesjavelona** [comment]
![stairs background](https://user-images.githubusercontent.com/7959179/28506036-637335a4-6ff6-11e7-82a2-5ef88ba697cc.jpg)

**Comment by charlesjavelona** [comment]
![background](https://user-images.githubusercontent.com/7959179/28506140-382e9068-6ff7-11e7-953f-76be897772e6.jpg)

**Comment by charlesjavelona** [comment]
![dsc_0417](https://user-images.githubusercontent.com/7959179/28558297-4a82b5e4-70df-11e7-9419-2ecb28356b54.png)

**Comment by charlesjavelona** [comment]
![charles_photo](https://user-images.githubusercontent.com/7959179/28581201-ab6bd05c-712f-11e7-80f0-4506ef71eddb.png)

**Comment by charlesjavelona** [comment]
![charles_photo](https://user-images.githubusercontent.com/7959179/28581201-ab6bd05c-712f-11e7-80f0-4506ef71eddb.png)

**Comment by charlesjavelona** [comment]
![charles_png](https://user-images.githubusercontent.com/7959179/28581558-871c11d4-7130-11e7-8c04-65ccf94031ba.png)

**Comment by charlesjavelona** [comment]
![charles_png](https://user-images.githubusercontent.com/7959179/28581758-223075d4-7131-11e7-9200-fb2f991fbb9c.png)

**Comment by charlesjavelona** [comment]
![charles_png](https://user-images.githubusercontent.com/7959179/28581876-87cb4900-7131-11e7-8937-78a0485e33ba.png)

**Comment by charlesjavelona** [comment]
![charles_png](https://user-images.githubusercontent.com/7959179/28581912-a3cc24b2-7131-11e7-8869-983a1cbf39a2.png)

**Comment by charlesjavelona** [comment]
![Uploading charles_png.png…]()

**Comment by charlesjavelona** [comment]
![charles_png](https://user-images.githubusercontent.com/7959179/28582030-09001ea6-7132-11e7-8bec-e65f6a657bab.png)

**Comment by charlesjavelona** [comment]
![dsc_0408](https://user-images.githubusercontent.com/7959179/28594573-74d716da-715e-11e7-9f6e-f70a1f22dfd8.png)

**Comment by charlesjavelona** [comment]
![dsc_0430](https://user-images.githubusercontent.com/7959179/28595026-21686786-7160-11e7-9608-aff2652271ce.png)

**Comment by charlesjavelona** [comment]
![dsc_0425](https://user-images.githubusercontent.com/7959179/28595430-d7d6270a-7161-11e7-91fa-d172cbef1e60.png)
